### ISSUE TITLE
Error parsing post request data

### ISSUE THREAD

**Issue by nodatall** [vercel/micro#126]
Hello,
I am trying use micro to read data from a post request. This is the error I am running into: 
```
TypeError: "string" must be a string, Buffer, or ArrayBuffer
    at Function.byteLength (buffer.js:362:11)
    at send (/Users/nodatall/Documents/shuffle/retext-intepreter/node_modules/micro/dist/index.js:102:46)
    at /Users/nodatall/Documents/shuffle/retext-intepreter/node_modules/micro/dist/index.js:36:7
    at Generator.next (<anonymous>)
    at c (/Users/Sylvan/Documents/shuffle/retext-intepreter/node_modules/micro/dist/index.js:129:99)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
 This is the code I have written:
```js
const proofReadService = ( request, response ) => {
   return async function() {
    const data = await json(request)
    send( response, 200, 'hello world 👏')
  }
}

const cors = microCors({ allowMethods: ['PUT', 'POST'] })
module.exports = cors(proofReadService)
```
Here are the request headers:
```js
{ host: 'localhost:3000',
  connection: 'keep-alive',
  'content-length': '34',
  'postman-token': '4d7d2362-415b-2e47-29bc-fc2a938557b7',
  'cache-control': 'no-cache',
  origin: 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36',
  'content-type': 'application/json',
  accept: '*/*',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-US,en;q=0.8' } 
```
Any idea what might be going on? Thanks a bunch!

**Comment by timneutkens** [comment]
Hi, weird request, could you try removing the emoji?

**Comment by timneutkens** [comment]
Weird request has too much context. I meant i'm going to ask something weird ;)

**Comment by onbjerg** [comment]
This is because you are returning an async function, which is read as a non-null [here](https://github.com/zeit/micro/blob/master/lib/index.js#L36), which in turn makes micro try to send the function as a response (and it can't since responses can only be Buffers, strings or ArrayBuffers).

Could you try this code instead?

```js
const proofReadService = async (request, response) => {
  const data = await json(request)
  send(response, 200, 'hello world 👏')
}

const cors = microCors({ allowMethods: ['PUT', 'POST'] })
module.exports = cors(proofReadService)
```

**Comment by timneutkens** [comment]
@onbjerg you're totally right. Thanks ❤️

**Comment by azappa** [comment]
I'm using `microrouter`package with `micro-cors` but it gave me the errore described above.

Here part of my code (server host is `panda.dev:3401` while the page with ajax req is on `localhost:1337`) :
```javascript
const { send } = require('micro');
const { router, get, post } = require('microrouter');
const parse = require('urlencoded-body-parser');
const monk = require('monk');
const assert = require('assert');
const cors = require('micro-cors');
cors({
  allowMethods: ['GET', 'POST'],
  allowHeaders: ['Access-Control-Allow-Origin'],
  origin: 'http://localhost:1337',
});
<...>
const sendingdata = async (req, res) => {
  const _data = await parse(req);
  send(res, 200, _data); return;
};


module.exports = router(
  post('/sendingdata', cors(sendingdata)),
);
```
error is: `TypeError: "string" must be a string, Buffer, or ArrayBuffer`. Obviously the browser returns
 ```XMLHttpRequest cannot load http://panda.dev:3401/sendingdata. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:1337' is therefore not allowed access. The response had HTTP status code 500.```

**Comment by Obiwarn** [comment]
@azappa same here
