### ISSUE TITLE
"Argument name clash in strict mode" crash when starting

### ISSUE THREAD

**Issue by joshwcomeau** [vercel/micro#155]
Hi,

Following the basic example (fresh project, `npm i -S micro`, and run `micro` on a simple async function), I get the following error:

```
micro: Error when importing /Users/joshu/work/uncover-server/index.js: SyntaxError: Argument name clash in strict mode (3:37)
    at Parser.pp$5.raise (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:4333:13)
    at Parser.pp$2.checkLVal (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:3084:16)
    at Parser.checkLVal (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:5513:22)
    at Parser.pp$3.parseFunctionBody (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:4154:12)
    at Parser.parseFunctionBody (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:5289:20)
    at Parser.pp$1.parseFunction (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:2330:8)
    at Parser.pp$3.parseExprAtom (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:3576:21)
    at Parser.parseExprAtom (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:6591:22)
    at Parser.pp$3.parseExprSubscripts (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:3414:19)
    at Parser.pp$3.parseMaybeUnary (/Users/joshu/work/uncover-server/node_modules/micro/node_modules/babylon/lib/index.js:3394:19)
```

The file I'm running (that causes it to crash) is:

```js
const { json } = require('micro');

module.exports = async function(req, req) {
  const data = await json(req);

  console.log({ data });

  return 'Success!';
}
```

This bug appears to relate to babylon finding multiple variables named `async`?

The error occurs when I try to run using Node 7.5 and the harmony flag as well.

I tried using an earlier version of micro, but the same error occurs in 6.x and 5.x.

All in all, it's perplexing, since I can't get it to run at all with an async function.

Thanks, let me know if you need any more info from me.

**Comment by timneutkens** [comment]
@joshwcomeau could you provide an example? ❤️

**Comment by joshwcomeau** [comment]
@timneutkens certainly: https://github.com/joshwcomeau/Uncover-Server

It's literally the simplest possible example using async/await, haha. Which makes me think either a very recent sub-dependency has updated, or there's something wonky with my environment.

**Comment by timneutkens** [comment]
https://github.com/joshwcomeau/Uncover-Server/blob/master/index.js#L3 the argument names are req, req 😅

**Comment by joshwcomeau** [comment]
omg. Wow. Thank you, and sorry. Amazed I managed to mess up such a tiny file!

**Comment by timneutkens** [comment]
No worries! 😄 If you do find any bugs don't hesitate to notify us 👍

**Comment by yanlee26** [comment]
big bug!!!
