### ISSUE TITLE
Can't set headers after they are sent.

### ISSUE THREAD

**Issue by millette** [vercel/micro#213]
I was trying micro again, starting with the simplest readme examples.

This works, no errors or warning:
```
module.exports = () => 'Welcome to micro'
```

But I'm getting an unhandled rejection error when I hit localhost:3000 but I get the expected response in the browser::
```
module.exports = (req, res) => res.end('Welcome to micro')
```

The full error is:
```
Unhandled rejection Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at send (/home/millette/tim/node_modules/micro/lib/server.js:134:7)
    at sendError (/home/millette/tim/node_modules/micro/lib/server.js:144:5)
    at Promise.then.catch.err (/home/millette/tim/node_modules/micro/lib/server.js:36:19)
    at tryCatcher (/home/millette/tim/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/millette/tim/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/millette/tim/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/millette/tim/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/millette/tim/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/millette/tim/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/millette/tim/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/millette/tim/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

Finally, I got his working, no errors:

```
// npm
const send = require('micro').send

module.exports = (req, res) => send(res, 200, 'Welcome to micro')
```

**Comment by floatdrop** [comment]
@millette `res.end` returns `true`, which handled by `micro` as another response to send. This will work:

```js
module.exports = (req, res) => { res.end('Welcome to micro'); }
```
