### ISSUE TITLE
Generator error

### ISSUE THREAD

**Issue by daryl** [vercel/micro#45]
There seems to be an issue with generators, perhaps from `babel-plugin-transform-async-to-generator`.

This works:

``` javascript
export default async function(req, res) {
  ...
}
```

This doesn't:

``` javascript
async function anything(req, res) {
  ...
}

export default anything;
```

This will give me the following error:

```
> mic@1.0.0 start /Users/daryl/Desktop/mic
> micro --port 9000 index.js

/Users/daryl/Desktop/mic/index.js:8
  var ref = (0, _asyncToGenerator3.default)(_regenerator2.default.mark(function _callee() {
                                  ^

TypeError: Cannot read property 'default' of undefined
    at /Users/daryl/Desktop/mic/index.js:8:35
    at Object.<anonymous> (/Users/daryl/Desktop/mic/index.js:22:2)
    at Module._compile (module.js:398:26)
    at loader (/Users/daryl/Desktop/mic/node_modules/babel-register/lib/node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/daryl/Desktop/mic/node_modules/babel-register/lib/node.js:138:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/daryl/Desktop/mic/node_modules/micro/build/bin/micro:67:11)
```

**Comment by rauchg** [comment]
Yeah I've seen this. Do you have any suggestions @hzoo ?

**Comment by hzoo** [comment]
Yeah this would be a babel bug - hard to say what's going on without more information - what versions of babel plugins, config, output code. Might be an issue with the commonjs transform if that is what's being used (not necessarily the async code). It might be called before the import/require statement happens due to hoisting so it's undefined

**Comment by julianduque** [comment]
this seems related on how babel currently manages es6 modules, I want to investigate if using: https://www.npmjs.com/package/babel-plugin-add-module-exports fixes the issue

**Comment by hzoo** [comment]
Maybe, the plugin adds `module.exports = exports.default` if necessary and is only a problem if the module is actually exporting a default and you aren't using import/export syntax

**Comment by rauchg** [comment]
Should be gone
