### ISSUE TITLE
Error: listen EACCES: permission denied 127.0.0.1

### ISSUE THREAD

**Issue by ippezshelby** [vercel/micro#477]
Am getting permission errors even when I open command prompt as administrator.

```
micro: Accepting connections on port 3000
micro: Error: listen EACCES: permission denied 127.0.0.1
    at Server.setupListenHandle [as _listen2] (node:net:1415:21)
    at listenInCluster (node:net:1480:12)
    at Server.listen (node:net:1579:5)
    at startEndpoint (E:\APP\node_modules\micro\dist\src\bin\micro.js:123:12)
    at start (E:\APP\node_modules\micro\dist\src\bin\micro.js:145:13)
micro: Gracefully shutting down. Please wait...
```

**Environments:**

- OS - Windows 11
- Node JS - v16.17.1
- Micro JS - latest verion (10)

**Comment by oklas** [comment]
Solved in #481

**Comment by Hardik8491** [comment]
may be solve with restart system
