### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by MiguhRuiz** [vercel/micro#84]
I'm trying to start the micro service but an error on the console is displayed:

```
micro: Error when importing /Users/miguhruiz/Dropbox/dev/bettercode-api/projects.js: /Users/miguhruiz/Dropbox/dev/bettercode-api/projects.js:3
import { send, json } from 'micro'
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.require.extensions..js (/Users/miguhruiz/.nvm/versions/node/v6.4.0/lib/node_modules/micro/node_modules/async-to-gen/register.js:9:12)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/miguhruiz/.nvm/versions/node/v6.4.0/lib/node_modules/micro/bin/micro:60:9)
    at Module._compile (module.js:556:32)

```

**Comment by MiguhRuiz** [comment]
I can't understand it, the package.json has `babel-register`, `babel-plugin-transform-async-to-generator`, `babel-plugin-transform-runtime`, `babel-preset-es2015`, `babel-runtime` so the code might compile because micro works with ES6.

**Comment by leo** [comment]
We recently dropped support for ES6 in [6.0.0](https://github.com/zeit/micro/releases/tag/6.0.0). Please transpile the code by yourself (using gulp/webpack/rollup) if you still want to use these features... 😊

**Comment by MiguhRuiz** [comment]
But I'm using 6.4.0 :S

**Comment by leo** [comment]
@MiguhRuiz I'm talking about the version of micro 😄

**Comment by MiguhRuiz** [comment]
Alright, I'll use a transpiler. Thanks!!
